### PR TITLE
Add note to chapter 3 Readme that chapter 4 assumes you selected Amassador

### PR DESCRIPTION
**Pull request by CalRobert**
I would have liked to know that ch. 4 assumes you used Ambassador before making my selection for Ch. 3

### CODE REVIEW

**Comment by bikram20** [comment]
@CalRobert Thank you, and a great observation. I think we meant to use the Ambassador edge stack metrics (in chapter 4) as an example, but it does reflect as if it is a mandatory requirement. 

I would actually prefer to add the example of NGINX metrics and logs in chapter 4 and 5 respectively - in addition to Ambassador. 

@v-bpastiu Please fix these in the next iteration.

**Comment by CalRobert** [comment]
Thanks - would love to see Nginx added but this is my first time through!

**Comment by v-bpastiu** [comment]
Hi and thanks for the contribution. We will enhance the starter kit to include both services.

**Comment by v-bpastiu** [comment]
Hi, we have made some changes to the starter kit in relation to chapter 4. 
We have included the use of a sample app with regards to monitoring and removed the ambassador examples. 
Please see this PR with the changes made.
https://github.com/digitalocean/Kubernetes-Starter-Kit-Developers/pull/172

Thanks

**Pull request closed without merging**
