### PR TITLE
#162 update helm chart and image versions for sealed-secrets

### PR DESCRIPTION
**Pull request by aljorhythm**
issue #162
images were deleted from quay, see issue https://github.com/bitnami-labs/sealed-secrets/issues/822. updating tags resolves issues.

### CODE REVIEW

**Comment by v-bpastiu** [comment]
Hi and thanks for the PR. I would request that if we want to change the sealed secrets version from 2.0.2 to 2.1.6 we should also change the file names. For example:
`08-kubernetes-sealed-secrets/assets/manifests/sealed-secrets-values-v2.0.2.yaml` --> `08-kubernetes-sealed-secrets/assets/manifests/sealed-secrets-values-v2.1.6.yaml`.
The same should be done for `argocd/applications/helm` and `fluxcd/helm/releases` yaml files.
We should do this for consistency across the repository.
I hope this makes sense.

**Review by v-bpastiu — CHANGES_REQUESTED** [review]
Hi and thanks for the PR. I would request that if we want to change the sealed secrets version from 2.0.2 to 2.1.6 we should also change the file names. For example:
08-kubernetes-sealed-secrets/assets/manifests/sealed-secrets-values-v2.0.2.yaml --> 08-kubernetes-sealed-secrets/assets/manifests/sealed-secrets-values-v2.1.6.yaml.
The same should be done for argocd/applications/helm and fluxcd/helm/releases yaml files.
We should do this for consistency across the repository.
I hope this makes sense.

**Review by v-bpastiu — APPROVED** [review]

**Comment by aljorhythm** [comment]
@v-bpastiu renamed the filenames accordingly

**Comment by v-bpastiu** [comment]
Thanks @aljorhythm for the contribution.

**Comment by MattIPv4** [comment]
Hey, @aljorhythm - Thanks a ton for this sweet PR! 😄

Would you please shoot me an email when you get a chance?
mcowley at digitalocean dot com 🎉

**Pull request merged**
